### PR TITLE
[Compatibility Fix] Update sandbox example

### PR DESCRIPTION
**Pull request by Chaser**
This change will allow the sandbox example to compile with gcc 5.40 and CppUTest 3.8

### CODE REVIEW

**Comment by jwgrenning** [comment]
Hi Chaser, thanks for the contribution.  I noticed it a bit too late as I went through and made small code changes and a couple makefile changes to fix the build on my mac with cpputest 3.8 and clan 6.0.  I think some of the settings in the makefiles you made are no longer needed.  Would you mind checking to see if my changes fixed your build as well.  

Thanks, James

**Comment by Chaser** [comment]
Hello James, there were still some issues due to the clang > 7 having issues with reserved keywords.  I have updated the PR if you could please test that it is backwards compatible.

**Comment by jwgrenning** [comment]
Thanks again for the PR.

I had to add this for your change to work in clang 6

```
CPPUTEST_WARNINGFLAGS += -Wno-unknown-warning-option
```

Can you see if that works for you?

thanks, James

**Comment by Chaser** [comment]
Looks good with addition of CPPUTEST_WARNINGFLAGS += -Wno-unknown-warning-option.

**Pull request closed without merging**
